name: Instant Merge PRs

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - assigned
      - reopened
    paths:
      - README.md

permissions:
  packages: write
  contents: write
  id-token: write
  pull-requests: write
  checks: write
  security-events: write
  statuses: write

jobs:

  instant-merge:
    runs-on: ubuntu-latest
    steps:
      - id: poc
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          # echo "$GITHUB_CONTEXT"
          echo ${{ github.event.sender.id }}
          echo ${{ github.event.sender.login }}
      - name: force-merge
        if: ${{ github.event.sender.login == 'dchourasia' && startsWith(github.event.pull_request.title, 'Update README') }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh pr merge --merge --admin ${{ github.event.pull_request.html_url }}
